Simulation = "xgossip"
Servers = 1
Bf = 19
Suite = "bn256.G2"
CommunicationMode = 1
GossipPeers = 7
RoundsToSimulate = 5
MaxWeight = 100
LoadTime = 5
Timeout = 18000000
Hosts = 100

BlockSize, MinDelay, MaxDelay, UseSmart, IdaGossipEnabled, RoundTime
1000000, 244, 860, false, true, 25
1000000, 244, 860, true, true, 25