Simulation = "xgossip"
Servers = 1
Bf = 19
Suite = "bn256.G2"
CommunicationMode = 1
GossipTime = 150
GossipPeers = 8
BlockSize = 10000000
MaxRoundLoops = 3
RoundsToSimulate = 2
RoundTime = 25000
DefaultDelay = 4000
MinDelay = 1000
MaxDelay = 7000
UseSmart = true
MaxWeight = 100
LoadTime = 5
Timeout = 180

Hosts
20